### ISSUE TITLE
Final Flick submission. 

### ISSUE THREAD

**Issue by bry3133** [bry3133/Week1-Flicks#2]
My submission for week 1 Flicks assignment is complete! /cc @codepathreview

**Comment by codepathreview** [comment]
Hi @bry3133, I cannot build your project. Please push all of your project to the GitHub and notify me again by via cc @codepathreview.

**Comment by bry3133** [comment]
I am sorry for your troubles. This is the link to my new repository: https://github.com/bry3133/Week-1-MovieViewer /cc @codepathreview
